### ISSUE TITLE
Remix app is unable to connect to DB when deployed to Azure.

### ISSUE THREAD

**Issue by mex20** [aaronpowell/azure-remix-stack#7]
**Bug Description**
When I deployed this repo to Azure using ``` azd up ``` as recomended in the ``` /prisma/seed.ts ``` file, I get the error below. For some reason the remix app is unable to connect to the postgresql instance when it is running in Azure.

**Steps to reproduce:**
1. Clone this repo and run the dev container inside of it.
2. When the dev container is initialized, log into ``` azd ``` with the ``` azd login --use-device-code ``` command.
3. After a successful login, run the command ``` azd up ``` and answer the questions in the following dialog.
4. After a successful deployment, navigate to the produced ``` Endpoint ``` and try to log in with the credentials provided in the README.
5. See this error in the browser and the error below in the console: ![Screenshot 2023-01-20 at 9 23 24 PM](https://user-images.githubusercontent.com/12109514/213845002-6de86b69-55a8-4a0d-8882-c7ed23d464b3.png)

**Console Error:**

``` 2023-01-21T05:14:45.77271  Connecting to the container 'main'...

2023-01-21T05:14:45.78782  Successfully Connected to container: 'main' [Revision: 'ca-web-zpj7g4hsn3q5e--33qs0uf', Replica: 'ca-web-zpj7g4hsn3q5e--33qs0uf-8486759696-2g887']
2023-01-21T05:13:27.144270489Z 
2023-01-21T05:13:27.144274861Z Can't reach database server at `psql-db-zpj7g4hsn3q5e.postgres.database.azure.com`:`5432`
2023-01-21T05:13:27.144278759Z 
2023-01-21T05:13:27.144283149Z Please make sure your database server is running at `psql-db-zpj7g4hsn3q5e.postgres.database.azure.com`:`5432`.
2023-01-21T05:13:27.144287778Z     at RequestHandler.handleRequestError (/myapp/node_modules/@prisma/client/runtime/index.js:34316:13)
2023-01-21T05:13:27.144291493Z     at RequestHandler.request (/myapp/node_modules/@prisma/client/runtime/index.js:34293:12)
2023-01-21T05:13:27.144295489Z     at PrismaClient._request (/myapp/node_modules/@prisma/client/runtime/index.js:35273:16)
2023-01-21T05:13:27.144299564Z     at verifyLogin (/myapp/build/index.js:111:26)
2023-01-21T05:13:27.144303596Z     at action2 (/myapp/build/index.js:479:14)
2023-01-21T05:13:27.144306942Z     at Object.callRouteAction (/myapp/node_modules/@remix-run/server-runtime/dist/data.js:35:14)
2023-01-21T05:13:27.144310339Z     at handleDataRequest (/myapp/node_modules/@remix-run/server-runtime/dist/server.js:116:18)
2023-01-21T05:13:27.144313941Z     at requestHandler (/myapp/node_modules/@remix-run/server-runtime/dist/server.js:48:18)
2023-01-21T05:13:27.144317795Z     at /myapp/node_modules/@remix-run/express/dist/server.js:39:22 {
2023-01-21T05:13:27.144321674Z   clientVersion: '4.6.1',
2023-01-21T05:13:27.144325256Z   errorCode: undefined
2023-01-21T05:13:27.144329396Z }
2023-01-21T05:13:27.146333004Z POST /login?_data=routes%2Flogin 500 - - 5045.256 ms
2023-01-21T05:13:27.229181638Z GET /login?_data=root 200 - - 1.297 ms
2023-01-21T05:14:44.818299223Z GET /login?_data=routes%2Flogin 200 - - 2.002 ms
2023-01-21T05:14:44.819928833Z GET /login?_data=root 200 - - 0.999 ms

2023-01-21T05:15:17.502527331Z PrismaClientInitializationError: 
2023-01-21T05:15:17.502560236Z Invalid `prisma.user.findUnique()` invocation:
2023-01-21T05:15:17.502565036Z 
2023-01-21T05:15:17.502569184Z 
2023-01-21T05:15:17.502573770Z Can't reach database server at `psql-db-zpj7g4hsn3q5e.postgres.database.azure.com`:`5432`
2023-01-21T05:15:17.502577328Z 
2023-01-21T05:15:17.502583345Z Please make sure your database server is running at `psql-db-zpj7g4hsn3q5e.postgres.database.azure.com`:`5432`.
2023-01-21T05:15:17.502586974Z     at RequestHandler.handleRequestError (/myapp/node_modules/@prisma/client/runtime/index.js:34316:13)
2023-01-21T05:15:17.502590850Z     at RequestHandler.request (/myapp/node_modules/@prisma/client/runtime/index.js:34293:12)
2023-01-21T05:15:17.502594398Z     at PrismaClient._request (/myapp/node_modules/@prisma/client/runtime/index.js:35273:16)
2023-01-21T05:15:17.502598911Z     at verifyLogin (/myapp/build/index.js:111:26)
2023-01-21T05:15:17.502603695Z     at action2 (/myapp/build/index.js:479:14)
2023-01-21T05:15:17.502607903Z     at Object.callRouteAction (/myapp/node_modules/@remix-run/server-runtime/dist/data.js:35:14)
2023-01-21T05:15:17.502611587Z     at handleDataRequest (/myapp/node_modules/@remix-run/server-runtime/dist/server.js:116:18)
2023-01-21T05:15:17.502631731Z     at requestHandler (/myapp/node_modules/@remix-run/server-runtime/dist/server.js:48:18)
2023-01-21T05:15:17.502635831Z     at /myapp/node_modules/@remix-run/express/dist/server.js:39:22 {
2023-01-21T05:15:17.502641064Z   clientVersion: '4.6.1',
2023-01-21T05:15:17.502645171Z   errorCode: undefined
2023-01-21T05:15:17.502649064Z }
2023-01-21T05:15:17.504787869Z POST /login?_data=routes%2Flogin 500 - - 5005.932 ms

2023-01-21T05:15:17.594855249Z GET /login?_data=root 200 - - 1.197 ms
 ```

**Comment by mex20** [comment]
I have figured out the cause of this issue. The database is configured incorrectly. I believe that the Virtual Networking stuff in ```infra/core/database/postresl.bicep``` is getting in the way of connecting the other other resources in the stack. 

I have been able to work around this issue by adding the 'Allow all Azure resources' option in the Network option in the POSTGRESQL dashboard.

You can also edit the ```infra/core/database/postgres.bicep``` file to include this resource:

```
  resource SQLAllowAllWindowsAzureIps 'firewallRules' = {
    name: 'AllowAllWindowsAzureIps'
    properties: {
      startIpAddress: '0.0.0.0'
      endIpAddress: '0.0.0.0'
    }
  }
```

**Comment by aaronpowell** [comment]
My bad - I even knew I needed to add that but just forgot.

Put it in the main branch now.

**Comment by mex20** [comment]
No worries here! This is what Open Source is all about! We help each other build the best product possible!
